"""create table

Revision ID: 40eb9785f3d6
Revises: 
Create Date: 2024-07-26 16:16:10.327600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40eb9785f3d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('intensifier', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('has_sale', sa.BOOLEAN(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('coffee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('coffee')
    # ### end Alembic commands ###
