"""create column user.patronomic

Revision ID: 4ab73a78cab4
Revises: b789e598720f
Create Date: 2024-07-27 18:01:20.291139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ab73a78cab4"
down_revision: Union[str, None] = "b789e598720f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("patronomic", sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "patronomic")
    # ### end Alembic commands ###
