"""user.surname

Revision ID: b789e598720f
Revises: 40eb9785f3d6
Create Date: 2024-07-26 22:47:22.645855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b789e598720f"
down_revision: Union[str, None] = "40eb9785f3d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("surname", sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "surname")
    # ### end Alembic commands ###
