# Данные на случай если API будет снова лежать. Данное явление было замечено часто, status 500.
users = [
    {'name': 'John Smith',
     'has_sale': True,
     'address': {'street': '1235 Main St', 'city': 'Anytown', 'state': 'ANY', 'zip': '12345', 'country': 'Canada'}},
    {'name': 'Jane Doe',
     'has_sale': False,
     'address': {'street': '456 Oak Rd', 'city': 'Somewhere', 'state': 'ANY', 'zip': '67890', 'country': 'UK'}},
    {'name': 'Michael Johnson',
     'has_sale': True,
     'address': {'street': '789 Elm St', 'city': 'Elsewhere', 'state': 'ANY', 'zip': '54321', 'country': 'Australia'}},
    {'name': 'Emily Brown',
     'has_sale': False,
     'address': {'street': '321 Pine Ln', 'city': 'Nowhere', 'state': 'ANY', 'zip': '09876', 'country': 'Germany'}},
    {'name': 'David Lee',
     'has_sale': True,
     'address': {'street': '159 Oak Ave', 'city': 'Somewhere Else', 'state': 'ANY', 'zip': '13579', 'country': 'USA'}},
    {'name': 'Sarah Kim',
     'has_sale': False,
     'address': {'street': '753 Maple Rd', 'city': 'Nowhere Else', 'state': 'ANY', 'zip': '86420', 'country': 'France'}},
    {'name': 'Tom Wilson',
     'has_sale': True,
     'address': {'street': '951 Cedar Ln', 'city': 'Somewhere New', 'state': 'ANY', 'zip': '24680', 'country': 'Italy'}},
    {'name': 'Olivia Garcia',
     'has_sale': False,
     'address': {'street': '357 Birch St', 'city': 'Nowhere New', 'state': 'ANY', 'zip': '97531', 'country': 'Spain'}},
    {'name': 'Alex Nguyen',
     'has_sale': True,
     'address': {'street': '852 Oak Blvd', 'city': 'Somewhere Else', 'state': 'ANY', 'zip': '13579', 'country': 'USA'}},
    {'name': 'Emma Patel',
     'has_sale': False,
     'address': {'street': '654 Maple Ave', 'city': 'Nowhere Else', 'state': 'ANY', 'zip': '86420', 'country': 'Japan'}}
]


coffee = [
    {"title": "Arabica Coffee",
     "origin": "Ethiopia",
     "intensifier": "Medium roast",
     "notes": ["Citrus", "Sweet"]},
    {"title": "Colombian Coffee",
     "origin": "Colombia",
     "intensifier": "Dark roast",
     "notes": ["Chocolate", "Nutty"]},
    {"title": "America Blend",
     "origin": "Brazil, Colombia",
     "intensifier": "Medium-dark roast",
     "notes": ["Berry", "Creamy"]},
    {"title": "Kenyan Coffee",
     "origin": "Kenya",
     "intensifier": "Medium roast",
     "notes": ["Citrus", "Berry", "Floral"]},
    {"title": "Guatemalan Coffee",
     "origin": "Guatemala",
     "intensifier": "Medium-dark roast",
     "notes": ["Chocolate", "Nutty", "Caramel"]},
    {"title": "Sumatra Coffee",
     "origin": "Sumatra",
     "intensifier": "Dark roast",
     "notes": ["Earthy", "Spicy", "Herbal"]},
    {"title": "Costa Rican Coffee",
     "origin": "Costa Rica",
     "intensifier": "Medium roast",
     "notes": ["Floral", "Fruity", "Honey"]},
    {"title": "Jamaican Blue Mountain Coffee",
     "origin": "Jamaica",
     "intensifier": "Light roast",
     "notes": ["Delicate", "Smooth", "Balanced"]},
    {"title": "Ethiopian Yirgacheffe",
     "origin": "Ethiopia",
     "intensifier": "Medium roast",
     "notes": ["Floral", "Citrus", "Jasmine"]},
    {"title": "Kona Coffee",
     "origin": "Hawaii",
     "intensifier": "Medium-light roast",
     "notes": ["Bright", "Balanced", "Tropical"]}
]
