countries = [
    "Австралия",
    "Австрия",
    "Азербайджан",
    "Албания",
    "Алжир",
    "Ангола",
    "Андорра",
    "Аргентина",
    "Армения",
    "Афганистан",
    "Багамы",
    "Бангладеш",
    "Барбадос",
    "Бахрейн",
    "Беларусь",
    "Бельгия",
    "Бенин",
    "Болгария",
    "Боливия",
    "Босния и Герцеговина",
    "Ботсвана",
    "Бразилия",
    "Бруней",
    "Буркина-Фасо",
    "Бурунди",
    "Бутан",
    "Вануату",
    "Ватикан",
    "Великобритания",
    "Венгрия",
    "Венесуэла",
    "Вьетнам",
    "Габон",
    "Гаити",
    "Гайана",
    "Гамбия",
    "Гана",
    "Гватемала",
    "Гвинея",
    "Гвинея-Бисау",
    "Германия",
    "Гондурас",
    "Гренада",
    "Греция",
    "Грузия",
    "Дания",
    "Джибути",
    "Доминика",
    "Доминиканская Республика",
    "Египет",
    "Замбия",
    "Зимбабве",
    "Израиль",
    "Индия",
    "Индонезия",
    "Иордания",
    "Ирак",
    "Иран",
    "Ирландия",
    "Исландия"
]

teams = [
    "Utah Starzz",
    "San Antonio Spurs",
    "Houston Rockets",
    "Golden State Warriors",
    "Oklahoma City Thunder",
    "Los Angeles Lakers",
    "Los Angeles Clippers",
    "Denver Nuggets",
    "Minnesota Timberwolves",
    "Portland Trail Blazers",
    "Phoenix Suns",
    "Sacramento Kings",
    "Miami Heat",
    "Orlando Magic",
    "Atlanta Hawks",
    "Washington Wizards",
    "Charlotte Hornets",
    "Philadelphia 76ers",
    "New York Knicks",
    "Brooklyn Nets",
    "Boston Celtics",
    "Toronto Raptors",
    "Milwaukee Bucks",
    "Chicago Bulls",
    "Detroit Pistons",
    "Cleveland Cavaliers",
    "Indiana Pacers",
    "San Francisco Giants",
    "Chicago White Sox",
    "Houston Astros",
    "Los Angeles Angels",
    "Seattle Mariners",
    "Texas Rangers",
    "Oakland Athletics",
    "New York Yankees",
    "Boston Red Sox",
    "Toronto Blue Jays",
    "Baltimore Orioles",
    "Tampa Bay Rays",
    "Cleveland Indians",
    "Minnesota Twins",
    "Kansas City Royals",
    "Detroit Tigers",
    "Chicago Cubs",
    "St. Louis Cardinals",
    "Milwaukee Brewers",
    "Cincinnati Reds",
    "Pittsburgh Pirates",
    "Atlanta Braves",
    "Miami Marlins",
    "New York Mets",
    "Washington Nationals",
    "Philadelphia Phillies",
    "Los Angeles Dodgers",
    "Arizona Diamondbacks",
    "San Diego Padres",
    "Colorado Rockies",
    "San Francisco 49ers",
    "Arizona Cardinals",
    "Los Angeles Rams",
]

level: tuple = ('easy', 'hard', 'middle', 'middle')