groups:
  - name: Notification ContainerKilled
    interval: 10s
    rules:
      - alert: ContainerKilled
        expr: time() - container_last_seen > 60
        for: 0s
        labels:
          severity: warning
        annotations:
          summary: Container killed (instance {{ $labels.instance }})
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
